spring.application.name=courier-api
spring.datasource.url=jdbc:postgresql://localhost:5432/courier_db
spring.datasource.username=courier_user
spring.datasource.password=courier_pass

spring.kafka.bootstrap-servers=localhost:9092
spring.jpa.open-in-view=false